module.exports = {
    ACTIVE: "Active",
    PENDING: "Pending",
    INACTIVE: "Inactive",
    ARCHIVE: "Archive",
    LOCKED: "Locked",
    SALT_ROUNDS: 10,
    ALREADY_EXISTS: "Email id/phone already exists.",
    ALREADY_EXISTS_COMPANY: "Company with this CIN already exists.",
    INVALID_CREDENTIALS: "Invalid credentials",
    DUPLICATE: "Already exists",
    OTP_SENT: "OTP sent successfully",
    OTP_EXPIRE: 5,
    TOTAL_EQUITY_PERCENTAGE_NOT_EQUAL: "Total equity percentage should be 100",
    INVESTOR: "investor",
    CALL_CENTER: "call_center",
    USER_NOT_FOUND: "User not found",
    GRIEVANCE_NOT_FOUND: "Grievance not found",
    NOT_FOUND: "Not found",
    OTP_VERIFIED: "OTP verified successfully",
    INVALID_OTP: "Invalid OTP",
    APPLICANT: "APP",
    OTP_REGISTRATION_SUBJECT: "OTP for verification",
    PRE_ESTABLISHMENT: "pre_establishment",
    OTP: "Dear User, {{OTP}} is your OTP. Thank you for choosing SWC",
    SUCCESS: "success",
    FORGOT_PASSWORD: "Forgot Password",
    UPDATE_NUMBER: "Update Number",
    INVALID_PASSWORD: "Invalid Password",
    FAIL: "Fail, try again later",
    WITHDRAWAL_LIMIT_EXCEED: "Withdrawal limit exceed",
    INSUFFICIENT_BALANCE: "Insufficient balance",



    /// user default 
    imageBaseUrl: "http://192.168.29.226:3000/",
    appName: "MingleBeam",
    about: "I am using MingleBeam",
    aboutMe: "I am using MingleBeam to connect with people",
};
